"""AST-based SQL Validator & Guardrails for Database Agent.

Uses ``sqlglot`` to parse and validate SQL statements generated by the LLM,
ensuring **zero-risk** of SQL injection, data mutation, or destructive operations.

Security guarantees:
  - Only ``SELECT`` statements are permitted (including ``WITH ... SELECT``).
  - ``DROP``, ``DELETE``, ``UPDATE``, ``INSERT``, ``ALTER``, ``TRUNCATE``,
    and multi-statement queries are **immediately rejected**.
  - Missing ``LIMIT`` clauses are automatically injected (default: 1000).
  - Queries on large tables without ``WHERE`` clauses emit a warning.

Usage:
    from src.agents.db_agent.validator import validate_sql

    is_valid, sanitized_sql, error = validate_sql("SELECT * FROM rag_chunks")
    # is_valid=True, sanitized_sql="SELECT * FROM rag_chunks LIMIT 1000", error=""
"""

import logging
from typing import Any, Optional

import sqlglot
from sqlglot import exp
from sqlglot.errors import ErrorLevel

from src.shared.logger import get_logger

logger: logging.Logger = get_logger(__name__)

# Maximum rows returned by any query (auto-injected if missing)
_DEFAULT_LIMIT: int = 1000

# Statement types that are absolutely forbidden
_FORBIDDEN_TYPES: set[type] = {
    exp.Delete,
    exp.Insert,
    exp.Update,
    exp.Drop,
    exp.Alter,
    exp.Command,
}

# System Schemas and Tables Quarantine (AST Level)
_QUARANTINED_SCHEMAS: set[str] = {
    "information_schema",
    "pg_catalog",
    "pg_toast",
    "pg_temp",
}

_QUARANTINED_TABLES: set[str] = {
    "pg_tables",
    "pg_class",
    "pg_roles",
    "pg_user",
    "pg_shadow",
    "pg_authid",
    "pg_database",
    "pg_proc",
    "pg_namespace",
    "pg_attribute",
    "pg_stat_activity",
    "pg_settings",
    "pg_views",
    "pg_matviews",
    "pg_indexes",
    "pg_group",
    "pg_shshadow",
}

# Dangerous / DoS / Command / Exfiltration Functions Blacklist (AST Level)
_FORBIDDEN_FUNCTIONS: set[str] = {
    "pg_sleep",
    "pg_sleep_for",
    "pg_sleep_until",
    "pg_terminate_backend",
    "pg_cancel_backend",
    "dblink",
    "dblink_exec",
    "dblink_connect",
    "dblink_open",
    "query_to_xml",
    "query_to_xmlschema",
    "table_to_xml",
    "table_to_xmlschema",
    "cursor_to_xml",
    "cursor_to_xmlschema",
    "pg_read_file",
    "pg_read_binary_file",
    "pg_ls_dir",
    "pg_stat_file",
    "pg_write_file",
    "system",
    "sys_eval",
    "copy_to",
    "lo_export",
    "lo_import",
}

# Known large tables that SHOULD have a WHERE clause
_LARGE_TABLES: set[str] = {"rag_chunks", "knowledge_documents"}

# Keywords that must never appear in raw SQL (defence in depth)
_BLOCKED_KEYWORDS: list[str] = [
    "DROP ",
    "DELETE ",
    "TRUNCATE ",
    "ALTER ",
    "INSERT ",
    "UPDATE ",
    "GRANT ",
    "REVOKE ",
]


def validate_sql(
    raw_sql: str,
    default_limit: int = _DEFAULT_LIMIT,
    session_id: str = "N/A",
) -> tuple[bool, str, str]:
    """Validate and sanitize an LLM-generated SQL statement via AST parsing.

    Args:
        raw_sql: The raw SQL string produced by the LLM.
        default_limit: The ``LIMIT`` value to inject if none is present.
        session_id: Correlation ID for structured logging.

    Returns:
        A 3-tuple of ``(is_valid, sanitized_sql, error_message)``.

        - ``is_valid``: ``True`` if the statement passes all checks.
        - ``sanitized_sql``: The cleaned/normalised SQL (with LIMIT injected).
        - ``error_message``: Human-readable rejection reason (empty on success).
    """
    if not raw_sql or not raw_sql.strip():
        return False, "", "SQL statement is empty."

    clean_sql: str = raw_sql.strip().rstrip(";").strip()

    # ------------------------------------------------------------------
    # 1. Defence-in-depth: keyword blocklist (catches edge cases before parse)
    # ------------------------------------------------------------------
    upper_sql: str = clean_sql.upper()
    for keyword in _BLOCKED_KEYWORDS:
        if keyword in upper_sql:
            msg: str = (
                f"Security reject: Forbidden keyword '{keyword.strip()}' "
                f"detected in SQL statement."
            )
            logger.warning(msg, extra={"session_id": session_id})
            return False, "", msg

    # ------------------------------------------------------------------
    # 2. Parse with sqlglot
    # ------------------------------------------------------------------
    try:
        expressions: list[exp.Expression] = sqlglot.parse(
            clean_sql, dialect="postgres", error_level=ErrorLevel.RAISE
        )
    except Exception as exc:
        msg = f"SQL parse error: {exc}"
        logger.warning(msg, extra={"session_id": session_id})
        return False, "", msg

    # ------------------------------------------------------------------
    # 3. Multi-statement check
    # ------------------------------------------------------------------
    if len(expressions) != 1:
        msg = (
            f"Security reject: Multi-statement SQL detected "
            f"({len(expressions)} statements). Only single SELECT is allowed."
        )
        logger.warning(msg, extra={"session_id": session_id})
        return False, "", msg

    statement: exp.Expression = expressions[0]

    # ------------------------------------------------------------------
    # 4. Statement type whitelist (only SELECT / UNION allowed)
    # ------------------------------------------------------------------
    for forbidden_type in _FORBIDDEN_TYPES:
        if isinstance(statement, forbidden_type):
            msg = (
                f"Security reject: Statement type "
                f"'{type(statement).__name__}' is not allowed. "
                f"Only SELECT queries are permitted."
            )
            logger.warning(msg, extra={"session_id": session_id})
            return False, "", msg

    # Check for forbidden nodes anywhere in the AST tree
    for node in statement.walk():
        for forbidden_type in _FORBIDDEN_TYPES:
            if isinstance(node, forbidden_type):
                msg = (
                    f"Security reject: Forbidden sub-expression "
                    f"'{type(node).__name__}' found in AST tree."
                )
                logger.warning(msg, extra={"session_id": session_id})
                return False, "", msg

    # Ensure root is SELECT or a CTE wrapping SELECT
    if not isinstance(statement, (exp.Select, exp.Union, exp.Intersect, exp.Except)):
        # Could be a CTE — check if it ends with a SELECT
        subqueries = list(statement.find_all(exp.Select))
        if not subqueries:
            msg = (
                f"Security reject: Root statement is "
                f"'{type(statement).__name__}', not SELECT."
            )
            logger.warning(msg, extra={"session_id": session_id})
            return False, "", msg

    # Strict Read-Only: Reject SELECT ... INTO and Locking clauses (FOR UPDATE / FOR SHARE)
    if statement.find(exp.Into):
        msg = "Security reject: SELECT INTO / Table mutation clause is strictly forbidden."
        logger.warning(msg, extra={"session_id": session_id})
        return False, "", msg

    if statement.find(exp.Lock):
        msg = "Security reject: Locking clause (FOR UPDATE/SHARE) is strictly forbidden in read-only queries."
        logger.warning(msg, extra={"session_id": session_id})
        return False, "", msg

    # ------------------------------------------------------------------
    # 5. Schema & System Table Quarantine
    # ------------------------------------------------------------------
    for table in statement.find_all(exp.Table):
        t_name = (table.name or "").lower()
        t_db = (table.db or "").lower()
        if t_db in _QUARANTINED_SCHEMAS:
            msg = f"Security reject: Access to quarantined system schema '{t_db}' is forbidden."
            logger.warning(msg, extra={"session_id": session_id})
            return False, "", msg
        if t_name in _QUARANTINED_TABLES:
            msg = f"Security reject: Access to quarantined system table '{t_name}' is forbidden."
            logger.warning(msg, extra={"session_id": session_id})
            return False, "", msg

    # ------------------------------------------------------------------
    # 6. Function Blacklist (DoS, File I/O, Privilege Escalation)
    # ------------------------------------------------------------------
    for func in statement.find_all(exp.Func, exp.Anonymous):
        func_name = (func.name or func.key or "").lower()
        if func_name in _FORBIDDEN_FUNCTIONS:
            msg = f"Security reject: Function '{func_name}()' is blacklisted (potential DoS/Privilege Escalation)."
            logger.warning(msg, extra={"session_id": session_id})
            return False, "", msg

    # ------------------------------------------------------------------
    # 7. Auto-inject LIMIT if missing
    # ------------------------------------------------------------------
    has_limit: bool = statement.find(exp.Limit) is not None
    if not has_limit:
        try:
            statement = statement.limit(default_limit)
            logger.info(
                "Auto-injected LIMIT %d into SQL query",
                default_limit,
                extra={"session_id": session_id},
            )
        except Exception:
            # If limit injection fails, append manually
            pass

    # ------------------------------------------------------------------
    # 8. WHERE clause warning for large tables
    # ------------------------------------------------------------------
    tables_referenced: list[str] = [
        t.name.lower()
        for t in statement.find_all(exp.Table)
        if t.name
    ]
    has_where: bool = statement.find(exp.Where) is not None

    for table_name in tables_referenced:
        if table_name in _LARGE_TABLES and not has_where:
            logger.warning(
                "SQL Guardrail Warning: Query on large table '%s' "
                "has no WHERE clause. Consider adding filters.",
                table_name,
                extra={"session_id": session_id},
            )

    # ------------------------------------------------------------------
    # 9. Generate sanitized SQL from the validated AST
    # ------------------------------------------------------------------
    sanitized: str = statement.sql(dialect="postgres")

    logger.info(
        "SQL Validator PASSED: %s",
        sanitized[:100],
        extra={"session_id": session_id},
    )

    return True, sanitized, ""


def parameterize_sql(sql: str, dialect: str = "postgres") -> tuple[str, list[Any]]:
    """Extract literal constants from SQL AST and replace with $1, $2, ... positional parameters.

    Ensures 100% prepared statement execution on asyncpg, eliminating SQL injection risk.
    Leaves LIMIT and OFFSET integers in place for execution compatibility.

    Args:
        sql: Sanitized SQL string.
        dialect: SQL dialect (default: 'postgres').

    Returns:
        tuple[str, list[Any]]: (parameterized_sql, params_list)
    """
    if not sql or not sql.strip():
        return sql, []

    from typing import Any

    try:
        ast = sqlglot.parse_one(sql, read=dialect)
    except Exception as exc:
        logger.warning("Failed to parse SQL AST for parameterization: %s", exc)
        return sql, []

    params: list[Any] = []
    param_idx: int = 1

    # Traverse AST nodes to find literals
    for node in list(ast.walk()):
        if isinstance(node, exp.Literal):
            # Keep LIMIT and OFFSET literals inline
            parent = node.parent
            if parent and isinstance(parent, (exp.Limit, exp.Offset)):
                continue

            raw_val = node.this
            # Convert numeric or boolean types
            if node.is_number:
                val: Any = float(raw_val) if "." in str(raw_val) else int(raw_val)
            elif isinstance(raw_val, str) and raw_val.lower() in ("true", "false"):
                val = raw_val.lower() == "true"
            else:
                val = raw_val

            params.append(val)
            node.replace(exp.Parameter(this=exp.Literal.number(param_idx)))
            param_idx += 1

    parameterized_sql = ast.sql(dialect=dialect)
    logger.debug("Parameterize SQL: %s -> %s (params=%s)", sql[:80], parameterized_sql[:80], params)
    return parameterized_sql, params

