import type { DashboardLanguage } from './types';

const TEXT = {
  en: {
    story: 'Data story',
    actions: 'What to do next',
    watch: 'Keep in mind',
    questions: 'Questions to explore',
    filters: 'Filters',
    all: 'All',
    clear: 'Clear filters',
    filtering: 'Recomputing…',
    filterError: 'Could not apply the filter',
    noData: 'Not enough data for this chart after filtering',
    noRows: 'No rows match the selected filters',
    rows: 'rows',
    of: 'of',
    columns: 'columns',
    sampled: 'Analysed a random sample of {used} of {total} rows',
    tableNote: 'The grid shows the first {n} rows',
    quickSearch: 'Quick search…',
    exportCsv: 'CSV',
    exportPdf: 'PDF',
    exportPptx: 'PPTX',
    print: 'Print',
    fullscreen: 'Fullscreen',
    exitFullscreen: 'Exit fullscreen',
    collapse: 'Collapse table',
    expand: 'Expand table',
    verified: 'Every number verified against the data',
    unverified: 'Some numbers could not be verified',
    filterHint: 'Click a bar or slice to filter',
    exporting: 'Preparing the file…',
    exported: 'Downloaded',
    exportFailed: 'Export failed',
    cover: 'Data analysis report',
    insight: 'Insight',
    filteredNote: 'Findings describe the full dataset',
    showing: 'Showing',
    export: 'Export',
    details: 'Details',
    searchValues: 'Search values…',
    showMore: '+{n} more',
    showLess: 'Show less',
    retry: 'Try again',
  },
  vi: {
    story: 'Câu chuyện dữ liệu',
    actions: 'Nên làm gì tiếp theo',
    watch: 'Cần lưu ý',
    questions: 'Câu hỏi nên khám phá tiếp',
    filters: 'Bộ lọc',
    all: 'Tất cả',
    clear: 'Xóa bộ lọc',
    filtering: 'Đang tính lại…',
    filterError: 'Không áp dụng được bộ lọc',
    noData: 'Không đủ dữ liệu để vẽ biểu đồ này sau khi lọc',
    noRows: 'Không có dòng nào khớp với bộ lọc',
    rows: 'dòng',
    of: 'trên',
    columns: 'cột',
    sampled: 'Đã phân tích mẫu ngẫu nhiên {used} trên {total} dòng',
    tableNote: 'Bảng hiển thị {n} dòng đầu tiên',
    quickSearch: 'Tìm nhanh…',
    exportCsv: 'CSV',
    exportPdf: 'PDF',
    exportPptx: 'PPTX',
    print: 'In',
    fullscreen: 'Toàn màn hình',
    exitFullscreen: 'Thu nhỏ',
    collapse: 'Thu gọn bảng',
    expand: 'Mở rộng bảng',
    verified: 'Mọi con số đã được đối chiếu với dữ liệu',
    unverified: 'Một số con số chưa được kiểm chứng',
    filterHint: 'Bấm vào cột hoặc lát cắt để lọc',
    exporting: 'Đang chuẩn bị tệp…',
    exported: 'Đã tải xuống',
    exportFailed: 'Xuất tệp thất bại',
    cover: 'Báo cáo phân tích dữ liệu',
    insight: 'Nhận định',
    filteredNote: 'Các nhận định mô tả toàn bộ dữ liệu',
    showing: 'Hiển thị',
    export: 'Xuất tệp',
    details: 'Chi tiết',
    searchValues: 'Tìm giá trị…',
    showMore: '+{n} giá trị',
    showLess: 'Thu gọn',
    retry: 'Thử lại',
  },
} as const;

export type UiKey = keyof (typeof TEXT)['en'];

/** UI string in the dashboard's language; ``{name}`` placeholders are filled from ``params``. */
export function ui(lang: DashboardLanguage | undefined, key: UiKey, params?: Record<string, string | number>): string {
  const template: string = TEXT[lang === 'vi' ? 'vi' : 'en'][key];
  return params ? template.replace(/\{(\w+)\}/g, (_, name) => String(params[name] ?? '')) : template;
}
